### PR TITLE
Fix : adding defensive code.

### PR DESCRIPTION
**Pull request by nicoaldegheri**

### CODE REVIEW

**Comment by mRs-** [comment]
Is this really an issue? I mean, it should be natural that there is something wrong when you hand in a emtpy string ^_^

**Comment by nicoaldegheri** [comment]
You're right, this is not really a fix, this is more a improvement for my comfort and perhaps for other people ;-)
 I propose this change so that both methods (hx_colorWithHexString: and hx_colorWithHexString:alpha:) have the same behavior.
Actually if you pass a nil or empty string to hx_colorWithHexString: the result is white color but if you do the same in hx_colorWithHexString:alpha: the result is nil and that is I think this is the right way to deal with nil argument :-)

**Comment by mRs-** [comment]
That's a point! It will be considered in 3.1.0

**Comment by mRs-** [comment]
Hey @nicoaldegheri I just created a new pull request (https://github.com/mRs-/HexColors/pull/30) for better nullability and a code cleanup

**Pull request closed without merging**
