### PR TITLE
Fixed app store submission issue with LLVM instrumentation symbols

### PR DESCRIPTION
**Pull request by treyrich**

### CODE REVIEW

**Comment by mRs-** [comment]
why exactly should I remove the test coverage here?

**Comment by treyrich** [comment]
Because Apple now rejects binaries that include LLVM instrumentation symbols. So if a developer includes this framework in their project via Carthage, they’d have to manually make this change to your project every time it was updated if they wanted to submit to Apple. 

I’m sure there are other ways that you could approach this problem, but ultimately the project as-is breaks App Store submission when included as a dependency. 

Here are a couple of resources that add more explaination. 

https://forums.developer.apple.com/thread/81893

http://blog.carlossless.io/xcode-9-and-carthage-coverage-data

**Comment by mRs-** [comment]
Is it really necessary to disable code coverage for the test schemes? It would break the current code coverage system by codecoverage.io

**Comment by treyrich** [comment]
I believe that it is necessary...But I'm not an expert by any means. From what I attempted, this PR represents the smallest changes that could be made to allow iTunes Connect to accept a build.

You can easily test alternative solutions though, simply use Xcode 9 to build and submit a sample project to iTunes Connect, if it processes correctly then you're golden, but if it doesn't work then you'll receive an email saying that your binary was rejected.

**Comment by mRs-** [comment]
Will give this a try soon. Currently I got no Carthage project around to test it.

**Comment by treyrich** [comment]
@mRs- any chance this could be merged?

**Comment by mRs-** [comment]
You should use **copy-frameworks.sh** from carthage. This will fix this problem

**Pull request closed without merging**
