### PR TITLE
Added prefix to all the category methods

### PR DESCRIPTION
**Pull request by buscarini**
This should avoid conflicts with other libraries (which I just had).

### CODE REVIEW

**Comment by mRs-** [comment]
Thanks for the contribution. I will create a new major release out of this, because it's API breaking changes

**Comment by n-studio** [comment]
The 2.3 API enabled to write UIColor(hexString: "ff0000"), but the new API doesn't allow UIColor(hx_hexString: "ff0000")...
This is not really swift-friendly...

**Comment by mRs-** [comment]
Yeah I know there is a Problem with the short-hand calls on swift, this problem is caused by the compiler and you have to move your implementation the class calls

```
UIColor.hx_colorWith8BitRed(33, green: 44, blue: 66)
UIColor.hx_colorWith8BitRed(22, green: 33, blue: 44, alpha: 0.3)
UIColor.hx_colorWithHexString("AAEEFF")
UIColor.hx_colorWithHexString("AAEEFF", alpha: 0.2)
```

**Comment by mRs-** [comment]
I added examples to the Readme.md

**Pull request merged**
