### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by chrene**
Adds carthage support. I also added an 's' to the files. Otherwise the frameworks didn't work

### CODE REVIEW

**Comment by mRs-** [comment]
awesome!

**Comment by mRs-** [comment]
@chrene can you update the pull request with your current develop?

**Comment by chrene** [comment]
@mRs- I think it's the latest. However it has conflicts since I've renamed the framework.

**Comment by mRs-** [comment]
Yeah i renamed the Framework too. I have no experience in using Carthage, what files are crucial for supporting it?

**Comment by chrene** [comment]
The crucial part is only to make the build schemes shared. This is getting a bit old, so I have to checkout your newest branch to see if the problem is still their

**Pull request merged**
