### PR TITLE
Allow colorWithHexString: to take a 5 or 9 character string that include alpha

### PR DESCRIPTION
**Pull request by nfranke**

### CODE REVIEW

**Comment by tbaranes** [comment]
Any news about this pull request? That should be great!

**Comment by mRs-** [comment]
Yeah I look into this today!

**Comment by rsanchezsaez** [comment]
'Today' seems to be an elusive date. ;-)

**Comment by mRs-** [comment]
Good weather, BBQ and Beer are some major priorities on my duty list. Today the Weather is really shitty here, maybe I have some free time and it is on my ToDo List

**Comment by rsanchezsaez** [comment]
Hahaha! ;)

**Pull request merged**
